<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <header>

    </header>
    <main>
        <h2>Bienvenue sur ce blog</h2>
        <h3>Retrouvez ici nos derniers articles</h3>

        <ul>
            <?php foreach($articles as $line): ?>
                <li><a href="#"><?= $line->getTitle() ?></a></li>
            <?php endforeach; ?>
        </ul>
    </main>
</body>
</html>