<h2>Ajouter un nouvel article</h2>
<form method="POST">
    <div class="form-group">
        <label for="title">Titre de l'article</label>
        <input type="text" name="title" id="title">
    </div>
    <div class="form-group">
        <label for="content">Contenur de l'article</label>
        <textarea name="content" id="content" cols="30" rows="10"></textarea>
    </div>
    <div class="form-group">
        <label for="categorie">Catégorie</label>
        <select name="categorieId" id="categorie">
            <?php foreach ($cats as $cat) : ?>
                <option value="<?= $cat->getId() ?>"><?= $cat->getName() ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <div class="form-group">
        <button>Enregistrer</button>
    </div>
</form>