<h2>Ajouter un nouvel article</h2>

<form method="POST">
    <div class="form-group">
        <label for="title">Titre de l'article</label>
        <input type="text" name="title" id="title" value="<?= $article->title ?>">
    </div>
    <div class="form-group">
        <label for="content">Contenur de l'article</label>
        <textarea name="content" id="content" cols="30" rows="10"><?= $article->content ?></textarea>
    </div>
    <div class="form-group">
        <label for="categorie">Catégorie</label>
        <select name="categorie_id" id="categorie" value="<?= $article->categorie_id ?>">
            <?php foreach ($cats as $cat) : ?>
                <option value="<?= $cat->id ?>"><?= $cat->name ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <div class="form-group">
        <button>Enregistrer</button>
    </div>
</form>